### PR TITLE
@PlatformIO Library Registry manifest

### PR DESCRIPTION
**Pull request by ivankravets**
* Library Registry: https://platformio.org/lib
* Specification: [library.json](http://docs.platformio.org/page/librarymanager/config.html)
* Library Manager:  http://docs.platformio.org/page/librarymanager/index.html

### CODE REVIEW

**Comment by anion155** [comment]
I'm going to leave this rep for library continuation and use [uclibcpp-arduino](https://github.com/anion155/uclibcpp-arduino) as place for arduino related staff, to keep everything clean. And releases will be in uclibcpp-arduino rep.

**Comment by ivankravets** [comment]
Please fix this manifest https://github.com/anion155/uclibcpp-arduino/blob/master/library.json

**Comment by anion155** [comment]
done

**Comment by anion155** [comment]
Sorry, misslead.

**Comment by anion155** [comment]
Done

**Pull request closed without merging**
